import { Fragment, useState } from "react";
import { AlertTriangle, Check, Copy, Info, Lightbulb, Quote } from "lucide-react";

import { resolveMedia } from "@/lib/content";
import { cn } from "@/lib/utils";
import { Audio, Picture, Video } from "@/components/Media";

/**
 * Renders the AST produced by plugins/markdown.js.
 *
 * There is no parsing here. The tree arrives with code already tokenized and
 * maths already laid out, so this file is a switch statement over node types —
 * which is exactly what makes adding a custom block a small change.
 */

/* ── Inline ───────────────────────────────────────────────────────────── */

function Inline({ nodes, media }) {
  return (
    <>
      {nodes.map((node, i) => (
        <InlineNode key={i} node={node} media={media} />
      ))}
    </>
  );
}

function InlineNode({ node, media }) {
  switch (node.type) {
    case "text":
      return node.value;

    case "strong":
      return (
        <strong>
          <Inline nodes={node.children} media={media} />
        </strong>
      );

    case "emphasis":
      return (
        <em>
          <Inline nodes={node.children} media={media} />
        </em>
      );

    case "delete":
      return (
        <s className="text-muted-foreground">
          <Inline nodes={node.children} media={media} />
        </s>
      );

    case "inlineCode":
      return <code>{node.value}</code>;

    case "break":
      return <br />;

    case "link": {
      const external = /^https?:/.test(node.url);
      return (
        <a href={node.url} title={node.title ?? undefined} target={external ? "_blank" : undefined} rel={external ? "noreferrer noopener" : undefined}>
          <Inline nodes={node.children} media={media} />
        </a>
      );
    }

    case "image": {
      const image = resolveMedia(media, node.url);
      if (!image) return <span className="text-muted-foreground">[{node.alt || node.url}]</span>;
      return <Picture image={image} alt={node.alt ?? ""} className="border-border my-6 rounded-lg border" />;
    }

    case "math":
      // Generated by our own renderer at build time, never from user input.
      return <span dangerouslySetInnerHTML={{ __html: node.html }} />;

    case "footnoteRef":
      return (
        <sup id={`ref-${node.id}`}>
          <a href={`#fn-${node.id}`} className="text-brand px-0.5 font-mono text-xs">
            [{node.id}]
          </a>
        </sup>
      );

    default:
      return null;
  }
}

/* ── Code ─────────────────────────────────────────────────────────────── */

function CodeBlock({ node }) {
  const [copied, setCopied] = useState(false);

  const plain = node.lines.map((line) => line.map((token) => token.t).join("")).join("\n");
  const highlighted = new Set(node.highlight ?? []);
  const gutterWidth = String(node.lines.length).length;

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(plain);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      /* Clipboard is blocked in some embeds; the code is still selectable. */
    }
  };

  return (
    <div className="code-block not-prose group relative my-6">
      {(node.filename || node.lang) && (
        <div className="border-hairline text-muted-foreground flex items-center justify-between border-b px-4 py-2 font-mono text-xs">
          <span>{node.filename ?? node.lang}</span>
          {node.filename && node.lang && <span className="opacity-60">{node.lang}</span>}
        </div>
      )}

      <button
        type="button"
        onClick={copy}
        aria-label={copied ? "Copied" : "Copy code"}
        className="border-border bg-surface text-muted-foreground hover:text-foreground absolute right-2 top-2 rounded-md border p-1.5 opacity-0 transition-opacity focus-visible:opacity-100 group-hover:opacity-100"
        style={{ top: node.filename || node.lang ? "2.6rem" : "0.5rem" }}
      >
        {copied ? <Check size={14} aria-hidden="true" /> : <Copy size={14} aria-hidden="true" />}
      </button>

      <pre>
        <code>
          {node.lines.map((line, i) => (
            <span key={i} className="code-line" data-hl={highlighted.has(i + 1) ? "1" : undefined}>
              {node.numbers && (
                <span className="code-gutter" style={{ width: `${gutterWidth + 1}ch` }} aria-hidden="true">
                  {i + 1}
                </span>
              )}
              {line.map((token, j) =>
                token.c ? (
                  <span key={j} className={`tok-${token.c}`}>
                    {token.t}
                  </span>
                ) : (
                  <Fragment key={j}>{token.t}</Fragment>
                ),
              )}
              {"\n"}
            </span>
          ))}
        </code>
      </pre>
    </div>
  );
}

/* ── Directives ───────────────────────────────────────────────────────── */

const CALLOUTS = {
  note: { icon: Info, label: "Note", tone: "border-border" },
  finding: { icon: Lightbulb, label: "Finding", tone: "border-brand/40 bg-brand/5" },
  warning: { icon: AlertTriangle, label: "Warning", tone: "border-destructive/40" },
  aside: { icon: Quote, label: "Aside", tone: "border-hairline" },
};

function Gallery({ node, media }) {
  const images = (node.value ?? []).map((name) => ({ name, image: resolveMedia(media, name.split(/\s+/)[0]) })).filter((entry) => entry.image);

  if (!images.length) return null;

  // One image fills the measure; several tile. A two-column grid at three
  // images leaves an orphan, so three-up wins above two.
  const columns = images.length === 1 ? 1 : images.length === 2 ? 2 : 3;

  return (
    <div
      className={cn("not-prose my-8 grid gap-3", {
        "grid-cols-1": columns === 1,
        "grid-cols-2": columns === 2,
        "grid-cols-2 sm:grid-cols-3": columns === 3,
      })}
    >
      {images.map(({ name, image }) => (
        <Picture key={name} image={image} alt="" sizes={columns === 1 ? "(min-width: 1024px) 720px, 100vw" : "(min-width: 640px) 240px, 45vw"} className="border-border rounded-lg border" />
      ))}
    </div>
  );
}

function Directive({ node, media }) {
  const { name, attrs = {} } = node;

  if (name === "gallery") return <Gallery node={node} media={media} />;

  if (name === "video") {
    const src = attrs.src ?? node.value?.[0];
    return <Video video={resolveMedia(media, src)} poster={resolveMedia(media, attrs.poster)} caption={attrs.caption} loop={attrs.loop === true || attrs.loop === "true"} className="my-8" />;
  }

  if (name === "audio") {
    const src = attrs.src ?? node.value?.[0];
    return <Audio audio={resolveMedia(media, src)} caption={attrs.caption} />;
  }

  if (name === "figure") {
    const image = resolveMedia(media, attrs.src);
    if (!image) return null;
    return (
      <figure className="not-prose my-8">
        <Picture image={image} alt={attrs.alt ?? ""} className="border-border rounded-lg border" />
        {attrs.caption && <figcaption className="text-muted-foreground mt-2 text-sm">{attrs.caption}</figcaption>}
      </figure>
    );
  }

  const callout = CALLOUTS[attrs.type] ?? CALLOUTS[name] ?? CALLOUTS.note;
  const Icon = callout.icon;

  return (
    <aside className={cn("not-prose my-6 rounded-lg border p-4", callout.tone)}>
      <p className="text-muted-foreground flex items-center gap-2 font-mono text-xs">
        <Icon size={14} aria-hidden="true" />
        {attrs.title ?? callout.label}
      </p>
      <div className="prose mt-3 text-sm">
        <Block nodes={node.children} media={media} />
      </div>
    </aside>
  );
}

/* ── Blocks ───────────────────────────────────────────────────────────── */

function Block({ nodes, media }) {
  return (
    <>
      {nodes.map((node, i) => (
        <BlockNode key={i} node={node} media={media} />
      ))}
    </>
  );
}

function BlockNode({ node, media }) {
  switch (node.type) {
    case "paragraph": {
      // A paragraph holding only an image or a break would nest a figure
      // inside a <p>, which is invalid and breaks the layout.
      const onlyImage = node.children.length === 1 && node.children[0].type === "image";
      if (onlyImage) return <InlineNode node={node.children[0]} media={media} />;
      return (
        <p>
          <Inline nodes={node.children} media={media} />
        </p>
      );
    }

    case "heading": {
      const Tag = `h${Math.min(node.depth, 6)}`;
      return (
        <Tag id={node.id} className="group">
          <Inline nodes={node.children} media={media} />
          <a href={`#${node.id}`} aria-label="Link to this section" className="text-muted-foreground ml-2 opacity-0 no-underline transition-opacity group-hover:opacity-100 focus-visible:opacity-100">
            #
          </a>
        </Tag>
      );
    }

    case "list": {
      const Tag = node.ordered ? "ol" : "ul";
      return (
        <Tag start={node.ordered && node.start !== 1 ? node.start : undefined}>
          {node.children.map((item, i) => (
            <li key={i} className={item.checked !== null ? "list-none" : undefined}>
              {item.checked !== null && <input type="checkbox" checked={item.checked} readOnly className="accent-brand mr-2 align-middle" />}
              <Block nodes={item.children} media={media} />
            </li>
          ))}
        </Tag>
      );
    }

    case "blockquote":
      return (
        <blockquote>
          <Block nodes={node.children} media={media} />
        </blockquote>
      );

    case "code":
      return <CodeBlock node={node} />;

    case "math":
      return <div className="my-6 overflow-x-auto" dangerouslySetInnerHTML={{ __html: node.html }} />;

    case "thematicBreak":
      return <hr />;

    case "table":
      return (
        <div className="not-prose my-6 overflow-x-auto">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr>
                {node.header.map((cell, i) => (
                  <th key={i} className="border-border text-muted-foreground border-b pb-2 pr-4 text-left font-medium" style={{ textAlign: node.align[i] ?? undefined }}>
                    <Inline nodes={cell} media={media} />
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {node.rows.map((row, r) => (
                <tr key={r}>
                  {row.map((cell, c) => (
                    <td key={c} className="border-hairline border-b py-2 pr-4 align-top" style={{ textAlign: node.align[c] ?? undefined }}>
                      <Inline nodes={cell} media={media} />
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );

    case "directive":
      return <Directive node={node} media={media} />;

    default:
      return null;
  }
}

/* ── Root ─────────────────────────────────────────────────────────────── */

function Footnotes({ notes, media }) {
  if (!notes?.length) return null;

  return (
    <section className="border-hairline mt-14 border-t pt-6">
      <h2 className="sr-only">Footnotes</h2>
      <ol className="text-muted-foreground space-y-2 text-sm">
        {notes.map((note) => (
          <li key={note.id} id={`fn-${note.id}`} className="flex gap-3">
            <span className="text-brand shrink-0 font-mono text-xs leading-6">[{note.id}]</span>
            <span>
              <Inline nodes={note.children} media={media} />{" "}
              <a href={`#ref-${note.id}`} aria-label="Back to reference" className="text-muted-foreground no-underline">
                ↩
              </a>
            </span>
          </li>
        ))}
      </ol>
    </section>
  );
}

export default function Markdown({ ast, media, className }) {
  if (!ast?.children) return null;

  return (
    <div className={cn("prose", className)}>
      <Block nodes={ast.children} media={media} />
      <Footnotes notes={ast.footnotes} media={media} />
    </div>
  );
}
